### PR TITLE
Start work on overall puzzle class

### PR DESCRIPTION
**Pull request by Bluenix2**
I have created an overall puzzle class, with the file and folder name as described in the [`template`](https://github.com/Istalantar/SCJ-2021-classic-clownfish/tree/template) branch. So far it only splits the image, and converts it back to text when the `draw()` method is called.

I think this pull request should be merged into `main` before me and Tobi continue working.

### CODE REVIEW

**Comment by Tobi-De** [comment]
@Bluenix2 can you please describe what is happening in the init method of the puzzle class, I'm a bit confuse here, what does horizontal and vertical stand for? the puzzle class should expect an ascii art string, describe the process you used to create the puzzle pieces

**Comment by Bluenix2** [comment]
In the `__init__` we get a string, and need to convert it to several pieces (segments) of it.

At first I decided to save us some potential headaches later, so I also do some validation to make sure the image is even and that it can be evenly split. `horizontal` and `vertical` are the amount of pieces. That is, for a 4-piece puzzle they are 2 and 2 respectively.

We take `horizontal` and `vertical` and convert it to how many characters each piece will be. In our 4-piece scenario say the puzzle is a 40 character square, `width` and `height` will be 20 and 20 respectively. In Python when you do division you get a float back, so we make sure we don't have decimals (how do you split a character?).

After this we initialize a 2 dimensional list of PuzzlePiece instances to support splitting the image. The big loop you see is the *actual splitting*, we go through each line, and for each line we go through X segments (x being `horizontal`). The `walk` function is a shortcut, you can see it above:
```py
def walk(string: str, step: int) -> str:
    """Helper generator to iterate over a string with steps"""
    for i in range(0, len(string), step):
        yield string[i:i+step]
```

The `walk` function *walks* the string based on `step`.

At last I use the indexes of the lines and columns to find the index of the piece. On line 34 character 20 we get: `34 // 20 = 1` and `20 // 20 = 1`.

**Comment by Bluenix2** [comment]
```py
for i, line in enumerate(data):
    for j, column in enumerate(walk(line, width)):
        pieces[i//height][j//width].append(column)
```
Is actually the same as this much more complicated code that I first made:
```py
# Create and go through each row of the image
for i, row in zip(range(len(data)), range(0, len(data), height)):
    # Go through each line in the row
    for line in data[row:row+height]:
        # Create and go through each column of the image
        for j, column in zip(range(len(line)), range(0, len(line), width)):
            # Add the segment of the string to the piece
            pieces[i][j].append(line[column:column+width])
```

**Comment by Tobi-De** [comment]
Well now it's clearer, for any image I think the puzzle will be a square, so ```horizontal``` and ``` vertical``` are likely to always be of the same value, we can replace them with one parameter, this will simplify the rest of your checks.

There is also few missing things, your ```draw``` method is missing a way to add borders to the puzzle, you can add a private method ```add_border``` which we'll implement  later and call it in the ```draw``` method, we also need a way to know when the puzzle is solved, so the puzzle class needs an attribute to store the original image, or the original pieces if you prefer. 
You can also add boilerplate methods to handle the movement, we can have a method to handle each direction (the best option I think), or a generic method that takes ```direction``` as an argument.

**Comment by Bluenix2** [comment]
> Well now it's clearer, for any image I think the puzzle will be a square, so `horizontal` and ` vertical` are likely to always be of the same value, we can replace them with one parameter, this will simplify the rest of your checks.

I disagree, I don't think this will simplify it too much. And we may have rectangular images

> There is also few missing things, your `draw` method is missing a way to add borders to the puzzle, you can add a private method `add_border` which we'll implement later and call it in the `draw` method, we also need a way to know when the puzzle is solved, so the puzzle class needs an attribute to store the original image, or the original pieces if you prefer.
> You can also add boilerplate methods to handle the movement, we can have a method to handle each direction (the best option I think), or a generic method that takes `direction` as an argument.

Yes I have yet to implement these, I wanted this to be a start of assembling and disassembling the puzzle. What you have pointed out is what we're gonna work on now moving forward.

**Comment by Tobi-De** [comment]
> I disagree, I don't think this will simplify it too much. And we may have rectangular images

 rectangular puzzles?  like 4x5, I don't think we should allow that, but I'm not sure, it heavly depends on ificiana work, it is not a problem though, we can always update the code later

**Review by Tobi-De — APPROVED** [review]

**Pull request merged**
