### PR TITLE
Highscore

### PR DESCRIPTION
**Pull request by Istalantar**
Implements highscore functionality:
- read highscores from .csv file
- save highscore to .csv file
- display highscore as table, sorted after Time or Moves
- delete highscore

### CODE REVIEW

**Comment by Bluenix2** [comment]
Can you rebase this onto `main` rather than `template`? The way I interpreted the branch was that we were going to use it as a point of reference but not necessarily commit those changes.

**Comment by Istalantar** [comment]
I might have to clean up the branch, but the commits should not matter if I squash, right?

**Comment by Bluenix2** [comment]
In this case they will because you include commits from `template`.

**Comment by Istalantar** [comment]
The squash option literaly says: 'all 14 commits will be combined into one'
But I can try to rebase if you feel more comfortable with that

**Comment by Bluenix2** [comment]
I don't mean rebase merge on GitHub, I mean a rebase. This will remove `template`'s commits from this branch and base it on main. The way I thought we were gonna use `template` branch was only as a plan. Not what we actually include in the project. If `highscore` is merged into `main` we will also merge some of `template`'s commits into it.

**Comment by Istalantar** [comment]
I think I did the rebase wrong. Now all of my commits are on top of main. Now I'm afraid to push that.
And I still don't see, that the template commit will be seen in the main branch.
I thought that was the whole point of the squash option.

**Comment by Bluenix2** [comment]
> I think I did the rebase wrong. Now all of my commits are on top of main. Now I'm afraid to push that.

Can you send a screenshot of what the history looks like?

**Comment by Istalantar** [comment]
image

**Comment by Bluenix2** [comment]
Ah, yeah I don't think that's right. Assuming you have no un-pushed changes, reset all that.

**Pull request merged**
